version: '2'

services:
  go-sgx:
    image: enclaive/go-sgx
    container_name: "go-sgx"
    build:
      context: .
    ports:
      - "443:443"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
