version: '2'

services:
  golang-sgx:
    image: enclaive/golang-sgx
    container_name: "golang-sgx"
    build:
      context: .
    ports:
      - "443:443"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
